name: GITHUB 자동배포
on:
  push:
    branches:
      - main

jobs:
  Auto-Deploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: github repository
        uses: actions/checkout@v4

      - name: JDK17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application yml 추가
        run: |
          mkdir -p sec/main/resources || true
          echo "${{ secrets.APPICATION_YML }}" > ./src/main/resources/application.yml
          ls -al ./src/main/resources
          cat ./src/main/resources/application.yml
          
          
