name: GITHUB 자동배포
on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: github repository
        uses: actions/checkout@v4

      - name: JDK17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application yml 추가
        run: |
          mkdir -p src/main/resources || true
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
#          ls -al ./src/main/resources
#          cat ./src/main/resources/application.yml
          
      - name: jar(실행) 파일 생성하기
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: 빌드된 jar 파일 이름변경 및 이동
        run: |
          pwd
          mv ./build/libs/*SNAPSHOT.jar ./app.jar
          ls -al

  Deploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: app.jar 실행 파일을 ec2 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ./app.jar
          target: /home/ubuntu/prod/tobe
