name: GITHUB 자동배포
on:
  push:
    branches:
      - main

jobs:
  autodeploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: github repository
        uses: actions/checkout@v4

      - name: JDK17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

